name: Full Linter CSS + HTML
on:
  push:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Launch html Linter
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm install --global html-linter
      - run: html-linter --config ./.html-linter.json **/*.html

      - run: npm install --save-dev stylelint stylelint-config-standard 
      - run: npx stylelint --config ./.stylelint.json "**/*.css" --allow-empty-input

      - run: npm install eslint --save-dev
      - run: npx install-peerdeps --dev eslint-config-airbnb
      - run: npm install -D eslint-config-prettier eslint-plugin-prettier
      - run: npx eslint --config ./.eslintrc.json "**/*.js" --no-error-on-unmatched-pattern